### ISSUE TITLE
File reading issue

### ISSUE THREAD

**Issue by logicerpsolution** [jalik/jalik-ufs-gridfs#11]
Hi , I am getting  issue during the view file.  Files are successfully uploaded but getting error during the read file. When open file on Browser using "url" fields
```
Error: `value` required in setHeader("Content-Type", value).
  at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:342:11)
  at ServerResponse.res.setHeader 

   at packages/jalik:ufs/ufs-server.js:340:37
   at Domain.<anonymous> (packages/jalik:ufs/ufs-server.js:236:81)
   at Domain.run (domain.js:228:14)
   at packages/jalik:ufs/ufs-server.js:234:15
   at Object.handle (packages/jalik:ufs/ufs-server.js:188:39)
   at next
```

```
export const FilesStore = new UploadFS.store.GridFS({
--
  | collection: Files,
  | name: 'files',
  | chunkSize: 1024 * 255,
  | filter: new UploadFS.Filter({
  | contentTypes: ['application/pdf']
  | })

/* To upload file */
const upload = new UploadFS.Uploader({
--
  | data,
  | file,
  | store: FilesStore,
  | onError: reject,
  | onComplete: resolve
  | });
  | upload.start();
  |  
  | });

function uploadGridFS(uploadedFile) {
--
  | return new Promise((resolve, reject) => {
  | // pick from an object only: name, type and size
  |  
  | const file = {
  | name:uploadedFile.name,
  | type:uploadedFile.type,
  | size: uploadedFile.size   };
  | var data=uploadedFile;
  | const upload = new UploadFS.Uploader({
  | data,
  | file,
  | store: FilesStore,
  | onError: reject,
  | onComplete: resolve
  | });
  | upload.start();
  |  
  | });
  | }
```

**Comment by logicerpsolution** [comment]
I have resolve the issue , "type" filed must be inserted into database during file save.

**Comment by jalik** [comment]
@logicerpsolution automatic MIME type is detected by the browser when uploading file, it should not be set manually untill you are sure the file is of that type. But I am glad you have resolved your problem.
